site_name: Data platform | Developers design guide
# site_url: https://example.com
repo_url:   https://github.com/nhsengland/data-platform-design-guide
repo_name: Design guide page test
edit_uri: edit/main/docs/
plugins:
  - search
nav:
  - Home: index.md

theme:
  name: material
#   custom_dir: overrides
  palette:
    scheme: default
    primary: indigo
  font:
    text: Arial
  logo: images/nhs-blue-on-white.jpg
  favicon: images/favicon/favicon.ico
  features:
    - toc.integrate

extra_css:
  - extra.css
